# Generated by Django 5.2.6 on 2025-09-26 05:09

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RegistrationUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=70)),
                ('phone_number', models.CharField(max_length=15, validators=[django.core.validators.RegexValidator('^\\+?\\d{10,15}$', 'Enter a valid phone number (10–15 digits).')])),
                ('age', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(5), django.core.validators.MaxValueValidator(100)])),
                ('previous_qualification', models.CharField(max_length=50)),
                ('previous_qualification_percentage', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('email', models.EmailField(max_length=50, unique=True)),
                ('password', models.CharField(max_length=15)),
                ('confirm_password', models.CharField(max_length=15)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ClassSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(max_length=15, validators=[django.core.validators.RegexValidator('^\\+?\\d{10,15}$', 'Enter a valid phone number (10–15 digits).')])),
                ('slot', models.CharField(choices=[('Class 5-8 (Mon-Fri 4:00-5:00pm)', 'Class 5 to 8 - All Subjects (Mon-Fri 4:00pm - 5:00pm)'), ('Class 9-10 (Mon-Fri 6:00-7:00pm)', 'Class 9 & 10 - Science & Maths (Mon-Fri 6:00pm - 7:00pm)'), ('Class 11-12 (Mon-Fri 7:30-8:30pm)', 'Class 11 & 12 - PCM (Mon-Fri 7:30pm - 8:30pm)'), ('Special Class 5-8 (Sat-Sun 11:00-12:00pm)', 'Special Class 5 to 8 - All Subjects (Sat-Sun 11:00am - 12:00pm)'), ('Special Class 9-10 (Sat-Sun 4:00-5:00pm)', 'Special Class 9 & 10 - Science & Maths (Sat-Sun 4:00pm - 5:00pm)'), ('Special Class 11-12 (Sat-Sun 5:30-6:00pm)', 'Special Class 11 & 12 - PCM (Sat-Sun 5:30pm - 6:00pm)')], max_length=100)),
                ('booked_on', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tutorapp.registrationuser', to_field='email')),
            ],
        ),
    ]
