# Generated by Django 5.0.1 on 2025-09-23 09:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutorapp', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ClassSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slot', models.CharField(choices=[('Class 5-8 (Mon-Fri 4:00-5:00pm)', 'Class 5 to 8 - All Subjects (Mon-Fri 4:00pm - 5:00pm)'), ('Class 9-10 (Mon-Fri 6:00-7:00pm)', 'Class 9 & 10 - Science & Maths (Mon-Fri 6:00pm - 7:00pm)'), ('Class 11-12 (Mon-Fri 7:30-8:30pm)', 'Class 11 & 12 - PCM (Mon-Fri 7:30pm - 8:30pm)'), ('Special Class 5-8 (Sat-Sun 11:00-12:00pm)', 'Class 5 to 8 - All Subjects (Sat-Sun 11:00am - 12:00pm)'), ('Special Class 9-10 (Sat-Sun 4:00-5:00pm)', 'Class 9 & 10 - Science & Maths (Sat-Sun 4:00pm - 5:00pm)'), ('Special Class 11-12 (Sat-Sun 5:30-6:00pm)', 'Class 11 & 12 - PCM (Sat-Sun 5:30pm - 6:00pm)')], max_length=100)),
                ('booked_on', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
